<?php

/** Auto-generated by Craftable PRO */

namespace App\Models;

use App\Casts\JsonEncrypted;
use Illuminate\Database\Eloquent\Model;
use Spatie\Activitylog\LogOptions;
use Spatie\Activitylog\Traits\LogsActivity;

class ApiKey extends Model
{
    use LogsActivity;

    protected $table = 'api_keys';

    protected $fillable = [
        'name',
        'type',
        'key',
        'additional_data',
    ];

    public const TYPE_AMAZON = 'amazon';

    public const TYPE_SHOPIFY = 'shopify';

    public const TYPE_ETSY = 'etsy';

    public const TYPES = [
        self::TYPE_AMAZON,
        self::TYPE_SHOPIFY,
        self::TYPE_ETSY,
    ];

    protected $casts = [
        'key' => JsonEncrypted::class,
        'additional_data' => 'collection',
    ];

    public function getActivitylogOptions(): LogOptions
    {
        return LogOptions::defaults()
            ->logFillable()
            ->logOnlyDirty()
            ->dontSubmitEmptyLogs();
    }
}
