<?php

/** Auto-generated by Craftable PRO */

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Spatie\Activitylog\LogOptions;
use Spatie\Activitylog\Traits\LogsActivity;

class Order extends Model
{
    use LogsActivity;

    protected $table = 'orders';

    protected $fillable = [
        'order_id',
        'type',
        'order_date',
        'update_date',
        'order_status',
        'fulfillment',
        'sales_channel',
        'total_amount',
        'total_currency',
        'payment_method',
        'buyer_name',
        'address_line_1',
        'address_line_2',
        'city',
        'state',
        'postal_code',
        'country_code',
        'expected_ship_date',
        'is_shipped',
        'original_object',
    ];

    public function items(): HasMany
    {
        return $this->hasMany(OrderItem::class);
    }

    public function itemsByApiKey(): HasMany
    {
        return $this->hasMany(OrderItem::class, 'api_order_id', 'order_id');
    }

    public function getActivitylogOptions(): LogOptions
    {
        return LogOptions::defaults()
            ->logOnly([
                'order_id',
                'type',
                'order_date',
                'update_date',
                'order_status',
                'fulfillment',
                'sales_channel',
                'payment_method',
                'expected_ship_date',
                'is_shipped',
            ])
            ->logOnlyDirty()
            ->dontSubmitEmptyLogs();
    }
}
