<?php
/** Auto-generated by Craftable PRO */

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Ysell extends Model {


    protected $table = 'ysell';
    protected $fillable = [
        'api_key',
        'name',
    ];
}
